=== Politecnico-Jaime-Isaza/Hechos_Historicos/HechosHistoricos.dtd
<!ELEMENT HechosHistoricos (HechoHistorico)+>
        <!ELEMENT HechoHistorico (Fecha, Epoca?, PersonajeDestacado*)?>
        <!ELEMENT Epoca (Epoca1 | Epoca2)>
        <!ELEMENT Epoca1 (#PCDATA)>
        <!ELEMENT Epoca2 (#PCDATA)>
        <!ELEMENT PersonajeDestacado ANY>
        <!ELEMENT Nombre (#PCDATA)>
        <!ELEMENT FechaNacimiento (#PCDATA)>
        <!ELEMENT Fecha (#PCDATA | FormatoFecha)*>
        <!ELEMENT FormatoFecha (Dia,Mes,Año)>
        <!ELEMENT Dia (#PCDATA)>
        <!ELEMENT Mes (#PCDATA)>
        <!ELEMENT Año (#PCDATA)>
        <!ATTLIST HechoHistorico descripcion CDATA #REQUIRED>

=== Politecnico-Jaime-Isaza/Hechos_Historicos/HechosHistoricos.xml
<?xml version = "1.0" encoding = "UTF-8"?>

<!DOCTYPE HechosHistoricos SYSTEM "HechosHistoricos.dtd">

<HechosHistoricos>
    <HechoHistorico descripcion = "">
        <Fecha>
            <Dia></Dia>
            <Mes></Mes>
            <AÃ±o></AÃ±o>
        </Fecha>
        <Epoca>
            <Epoca1></Epoca1>
        </Epoca>
            <PersonajeDestacado>
                Test persona <Nombre></Nombre> y fecha de nacimiento <FechaNacimiento></FechaNacimiento>
            </PersonajeDestacado>
    </HechoHistorico>

</HechosHistoricos>
