=== Politecnico-Jaime-Isaza/Hechos_Historicos/Marcadores.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema">
    <xs:element name = "marcadores">
        <xs:complexType>
            <xs:sequence>
                <xs:element name = "pagina" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name = "nombre" type = "xs:string"/>
                            <xs:element name = "descripcion" type = "xs:string"/>
                            <xs:element name = "url" type = "xs:string"/>
                            <xs:element name = "aÃ±o">
                                <xs:simpleType>
                                    <xs:restriction base = "xs:integer">
                                        <xs:minInclusive value="2000"/>
                                        <xs:maxExclusive value="2020"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name = "tipo_pagina" maxOccurs="unbounded" minOccurs="0">
                                <xs:simpleType>
                                    <xs:restriction base = "xs:string">
                                        <xs:enumeration value = "educativa"/>
                                        <xs:enumeration value = "deportiva"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name = "correo">
                                <xs:simpleType>
                                    <xs:restriction base = "xs:string">
                                        <xs:pattern value="[a-z]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name = "ssl" type="xs:boolean" use = "required" fixed = "false"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Politecnico-Jaime-Isaza/Hechos_Historicos/Marcadores.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<marcadores xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation = "Marcadores.xsd">
    <pagina ssl = "false">
        <nombre>Abrirllave</nombre>
        <descripcion>Tutoriales de informatica</descripcion>
        <url>http://www.abrirllave.com</url>
        <año>2001</año>
        <tipo_pagina>deportiva</tipo_pagina>
        <correo>a</correo>
    </pagina>
    <pagina ssl = "false">
        <nombre>Wikipedia</nombre>
        <descripcion>La enciclopedia libre</descripcion>
        <url>http://www.wikipedia.org</url>
        <año>2017</año>
        <tipo_pagina>educativa</tipo_pagina>
        <correo>o</correo>
    </pagina>
    <pagina ssl = "false">
        <nombre>W3C</nombre>
        <descripcion>World Wide Web Construction</descripcion>
        <url>http://www.w3.org</url>
        <año>2019</año>
        <tipo_pagina>deportiva</tipo_pagina>
        <correo>c</correo>
    </pagina>
</marcadores>
